# Generated by Django 5.2.8 on 2025-11-25 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_type', models.CharField(max_length=64, verbose_name='駐車場タイプ')),
                ('rent_fee', models.IntegerField(verbose_name='月額使用料')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0, verbose_name='駐車No')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='契約者')),
                ('room_number', models.IntegerField(default=0, verbose_name='部屋番号')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='年月')),
                ('status_of_use', models.CharField(choices=[('使用中', '使用中'), ('空き', '空き'), ('一時利用', '一時利用'), ('予約中', '予約中'), ('解約予定', '解約予定'), ('使用中止', '使用中止')], default='使用中', max_length=32, verbose_name='利用状況')),
                ('comment', models.TextField(blank=True, verbose_name='備考')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('parking_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.parkingtype', verbose_name='駐車場タイプ')),
            ],
            options={
                'unique_together': {('no', 'payment_date')},
            },
        ),
    ]
