# Generated by Django 5.2.8 on 2025-11-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0, verbose_name='駐輪場No')),
                ('location', models.CharField(choices=[('棟前', '棟前'), ('棟東', '棟東'), ('棟北', '棟北'), ('平置き', '平置き')], default='棟前', max_length=4, verbose_name='駐輪場所')),
                ('room_number', models.IntegerField(default=0, verbose_name='部屋番号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='年月')),
                ('status_of_use', models.CharField(choices=[('空き', '空き'), ('使用中', '使用中'), ('契約予定', '契約予定'), ('解約予定', '解約予定')], default='空き', max_length=6, verbose_name='使用状況')),
                ('comment', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
    ]
