# 通帳監査システム
services:
  facility:
    # 相対パスでDockerfileのpathを指定。
    # contextは一つ上の階層なので、Dockerfileの指定はcontextで指定した階層からのpathになる。
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # image名:タグ
    image: facility
    # 起動ユーザを指定する
    user: "${UID}:${GID}"
    # container名
    container_name: facility
    restart: unless-stopped

    # ここで指定した中身が、OSの環境変数としてDjangoに渡される（settings.pyで読み込む）
    # 機密ファイル（.env）の配置場所を相対パスで指定
    env_file:
      - ../.env_dev

    # 開発環境では、ホスト上のルートディレクトリを/code/以下にマウントする。
    volumes:
      - ../:/code
      # ホストのoutputs/shared_data/facility_dataを、コンテナ内の/code/outputs/にマウントする。
      # ホストにはoutputs/shared_data/facility_dataが存在している必要がある。
      - ../../outputs/shared_data/facility_data/facility_data:/code/outputs
      # - ../../outputs/shared_data/parking_maps:/code/outputs/parking_maps

    # 環境変数を設定。
    environment:
      TZ: "Asia/Tokyo"

    # --------------------------------------------
    # ローカル環境ではportをオープンする。
    # --------------------------------------------
    ports:
      - "8300:8300"
    # Djangoの簡易サーバで起動する
    command: python3 manage.py runserver 0.0.0.0:8300
