# 使用するベースイメージ。
FROM python:3.13-slim
# stdoutへの出力をバッファリングさせない。(errorやlogを直ちに出力して欲しいから)
ENV PYTHONUNBUFFERED 1
# コンテナ環境にホストのマウント用にディレクトリを作成する。
RUN mkdir /code
# /code/ディレクトリを作業用ディレクトリにする。
WORKDIR /code
# requirements/以下の記述ファイルを/code/ディレクトリにコピーする。
COPY requirements /code/requirements
# pipでpythonパッケージをインストールする。
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements/dev.txt
