# local開発用
services:
  facility:
    build:
      context: ./
      dockerfile: Dockerfile
    # image名:タグ
    image: facility
    # container名
    container_name: facility
    restart: always
    # ホスト上のmeeting/ディレクトリをcode/としてコンテナにマウントする。
    volumes:
      - ../:/code
    # 環境変数TZを設定。
    environment:
      TZ: "Asia/Tokyo"
    # 開発環境 localテスト用にポートを公開。
    ports:
      - "8300:8300"

    command: python3 manage.py runserver 0.0.0.0:8300
