# Generated by Django 5.2.8 on 2025-12-05 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repair_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='KoujiRireki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2009)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('koujimei', models.CharField(max_length=256)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('constractor', models.CharField(blank=True, max_length=64, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rireki.accounttype')),
                ('koujitype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='repair_plan.masterkoujitype')),
            ],
        ),
    ]
