"""
Django settings for facility project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------
# 環境変数の読み込み
# ------------------------------------------------------------------
# instanceを作成
env = environ.Env(
    # 初期値を設定
    # SECURITY WARNING: don't run with debug turned on in production!
    # DEBUG=(bool, False)
)
# .envを読み込む
environ.Env.read_env(os.path.join(BASE_DIR, "docker/.env"))

# セキュリティ関係の環境変数を読み込む。
# 読み込む環境変数のタイプに合わせる必要があるので注意。
SECRET_KEY = env("SECRET_KEY")
DB_NAME = env("DB_NAME")
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# デフォルトは本番用なのでFalseとする。
DEBUG = False
# ローカル環境（local_settings.pyがあれば）でDEBUGを上書き
try:
    from .local_settings import DEBUG
except ImportError:
    pass

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-gdzgh6bh$_bf5l@w7!k8zqfo096r-%f_)n3a=w5+rx7j6vnj-8"

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "register.apps.RegisterConfig",
    "repair_plan.apps.RepairPlanConfig",
    "repair_plan_simulator.apps.RepairPlanSimulatorConfig",
    "repair_plan_cycle.apps.RepairPlanCycleConfig",
    "parking.apps.ParkingConfig",
    "bicycle.apps.BicycleConfig",
    "motorcycle.apps.MotorcycleConfig",
    "control.apps.ControlConfig",
    "shoukaki.apps.ShoukakiConfig",
    "rireki.apps.RirekiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "facility.middleware.UAmiddleware",
]

ROOT_URLCONF = "facility.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "facility.context_processors.global_settings",
            ],
            "libraries": {
                "my_templatetags": "templatetags.facility_extras",
            },
        },
    },
]

WSGI_APPLICATION = "facility.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / DB_NAME,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ------------------------------------------------------------------
# ユーザセッティング
# ------------------------------------------------------------------
# For Django4
CSRF_TRUSTED_ORIGINS = ["https://facility.sophiagardens.org"]
# カスタムユーザモデルを使う。
AUTH_USER_MODEL = "register.User"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
VERSION_NO = "2025-12-18"
LOGIN_URL = "register:login"
LOGIN_REDIRECT_URL = "register:mypage"
LOGOUT_REDIRECT_URL = "register:login"
# ブラウザを閉じたらログアウトさせる。
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# バックアップ数
BACKUP_NUM = 10
# 数値の3桁カンマ
NUMBER_GROUPING = 3
# マークダウンの拡張
MARKDOWN_EXTENSIONS = [
    "markdown.extensions.extra",
    "markdown.extensions.codehilite",
]

# -----------------------------------------------------------------------------
# static files settings
# -----------------------------------------------------------------------------
if DEBUG:
    # STATIC_ROOTに追加するパスを指定する。
    STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
else:
    # for nginx（本番のocker専用）
    STATIC_ROOT = "/code/static"

# -----------------------------------------------------------------------------
# 共用設備用設定
# -----------------------------------------------------------------------------
# 平置き
PLAIN_PARKING = "平置き"
# 機械式上部
MACHINE_UP_PARKING = "機械式上部"
# 機械式下部
MACHINE_DOWN_PARKING = "機械式下部"
# 駐輪場使用料
BICYCLE_USAGE_FEE = 200
# オートバイ使用料
MOTORCYCLE_USAGE_FEE = 1000
# 消火器廃棄年数
DISPOSAL_SHOUKAKI = 5

# -----------------------------------------------------------------------------
# 長期修繕計画用設定
# -----------------------------------------------------------------------------
# for accounting 第1期は1999年
INITIAL_YEAR = 1998

# -----------------------------------------------------------------------------
# ログ出力先のディレクトリを設定する
# -----------------------------------------------------------------------------
LOG_BASE_DIR = os.path.join(
    "logs",
)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {"simple": {"format": "%(asctime)s [%(levelname)s] %(message)s"}},
    # ログの出力方法についての設定。
    "handlers": {
        # DEBUG = Falseの場合、ログファイルに出力する。
        "info": {
            "level": "INFO",
            "filters": ["require_debug_false"],
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 51200,
            "backupCount": 5,
            "filename": os.path.join(LOG_BASE_DIR, "info.log"),
            "formatter": "simple",
        },
        "warning": {
            "level": "WARNING",
            "filters": ["require_debug_false"],
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 51200,
            "backupCount": 5,
            "filename": os.path.join(LOG_BASE_DIR, "warning.log"),
            "formatter": "simple",
        },
        # DEBUG = Trueの場合、コンソールにログ出力する。
        "debug": {
            "level": "DEBUG",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    # ロガーはルートロガーのみとする。levelはDEBUG以上とする。
    "root": {
        "handlers": ["info", "warning", "debug"],
        "level": "DEBUG",
    },
}
