"""
Django settings for facility project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# instanceを作成
env = environ.Env(
    # キャスト（型指定）とデフォルト値を設定
    DEBUG=(bool, False),
    SECRET_KEY=(str, ""),
    ALLOWED_HOSTS=(list, []),
)

# 1. まずOS自体の環境変数（またはデフォルト値）からモードを取得
# OS側に何もなければ 'development' とみなす
app_env = os.environ.get("APP_ENV", "development")

if app_env == "product":
    env_file = os.path.join(BASE_DIR, ".env")
else:
    env_file = os.path.join(BASE_DIR, ".env_dev")

# 読み込み実行
if os.path.exists(env_file):
    env.read_env(env_file)

# あとは共通：環境変数（OS由来 または .envファイル由来）から読み込む
SECRET_KEY = env("SECRET_KEY")
DB_NAME = env("DB_NAME")
ALLOWED_HOSTS = env("ALLOWED_HOSTS")
DEBUG = env("DEBUG")

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "common",
    "register.apps.RegisterConfig",
    "repair_plan.apps.RepairPlanConfig",
    "repair_plan_simulator.apps.RepairPlanSimulatorConfig",
    "repair_plan_cycle.apps.RepairPlanCycleConfig",
    "parking.apps.ParkingConfig",
    "bicycle.apps.BicycleConfig",
    "motorcycle.apps.MotorcycleConfig",
    "control.apps.ControlConfig",
    "shoukaki.apps.ShoukakiConfig",
    "rireki.apps.RirekiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "facility.middleware.UAmiddleware",
]

ROOT_URLCONF = "facility.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",  # プロジェクト直下の共通設定用テンプレートフォルダ
            BASE_DIR / "common" / "templates",  # commonアプリ用テンプレートフォルダ
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "facility.context_processors.global_settings",
            ],
            "libraries": {},
        },
    },
]

WSGI_APPLICATION = "facility.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / DB_NAME,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ------------------------------------------------------------------
# ユーザセッティング
# ------------------------------------------------------------------
# For Django4
CSRF_TRUSTED_ORIGINS = ["https://facility.sophiagardens.org"]
# カスタムユーザモデルを使う。
AUTH_USER_MODEL = "register.User"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
VERSION_NO = "2026-02-15"
LOGIN_URL = "register:login"
LOGIN_REDIRECT_URL = "register:mypage"
LOGOUT_REDIRECT_URL = "register:login"
# ブラウザを閉じたらログアウトさせる。
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# バックアップ数
BACKUP_NUM = 10
# 数値の3桁カンマ
NUMBER_GROUPING = 3
# マークダウンの拡張
MARKDOWN_EXTENSIONS = [
    "markdown.extensions.extra",
    "markdown.extensions.codehilite",
]

# -----------------------------------------------------------------------------
# 共用設備用設定
# -----------------------------------------------------------------------------
# 平置き
PLAIN_PARKING = "平置き"
# 機械式上部
MACHINE_UP_PARKING = "機械式上部"
# 機械式下部
MACHINE_DOWN_PARKING = "機械式下部"
# 駐輪場使用料
BICYCLE_USAGE_FEE = 200
# オートバイ使用料
MOTORCYCLE_USAGE_FEE = 1000
# 消火器廃棄年数
DISPOSAL_SHOUKAKI = 5

# -----------------------------------------------------------------------------
# 長期修繕計画用設定
# -----------------------------------------------------------------------------
# for accounting 第1期は1999年
INITIAL_YEAR = 1998

# -----------------------------------------------------------------------------
# ログ出力先のディレクトリを設定する
# -----------------------------------------------------------------------------
LOG_BASE_DIR = os.path.join(
    "logs",
)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {"simple": {"format": "%(asctime)s [%(levelname)s] %(message)s"}},
    # ログの出力方法についての設定。
    "handlers": {
        # DEBUG = Falseの場合、ログファイルに出力する。
        "info": {
            "level": "INFO",
            "filters": ["require_debug_false"],
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 51200,
            "backupCount": 5,
            "filename": os.path.join(LOG_BASE_DIR, "info.log"),
            "formatter": "simple",
        },
        "warning": {
            "level": "WARNING",
            "filters": ["require_debug_false"],
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 51200,
            "backupCount": 5,
            "filename": os.path.join(LOG_BASE_DIR, "warning.log"),
            "formatter": "simple",
        },
        # DEBUG = Trueの場合、コンソールにログ出力する。
        "debug": {
            "level": "DEBUG",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    # ロガーはルートロガーのみとする。levelはDEBUG以上とする。
    "root": {
        "handlers": ["info", "warning", "debug"],
        "level": "DEBUG",
    },
}

# -----------------------------------------------------------------------------
# static files settings
# 1. Dockerfileの "WORKDIR: /code"　、"COPY . /code"で code/ディレクトリにソースをコピー
#    dockerignoreファイルで、/static、/media、.env関連の機密ファイルはコピーから除外する
#    代わりにcompose.yml で /static、DBファイルはマウントして利用する
# 2. STATIC_ROOT はコピーした/code に static/ に colletstatic した結果を集約させる
#    static/ は STATIC_URL = "/static" で指定している
# -----------------------------------------------------------------------------

# 開発時に追加で参照するディレクトリ（共通のCSS/JSなど）
STATICFILES_DIRS = [
    BASE_DIR / "common" / "static",
]

# 開発（ローカル）ではプロジェクト直下の static フォルダに集める
if not DEBUG:
    # 本番環境
    # collectstatic で集約した静的ファイルのPath
    STATIC_ROOT = "/code/static"
else:
    # 開発環境
    # DEBUG=TrueではDjangoはこの設定を無視して、アプリ内のstatic/、STATICFILES_DIRSを直接参照する
    # ただし、開発環境で collectstatic を行う場合に必要となるため設定する
    STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
if not DEBUG:
    # MEDIA_ROOT = "/code_warehouse/media/"
    MEDIA_ROOT = "/code/media/"
else:
    MEDIA_ROOT = BASE_DIR / "media"



# # -----------------------------------------------------------------------------
# # static files settings
# # -----------------------------------------------------------------------------
# # 常に定義する
# STATIC_ROOT = "/code/static"

# if DEBUG:
#     # 開発時に追加で参照したい場合のみ
#     STATICFILES_DIRS = []
