# Generated by Django 5.2.8 on 2025-11-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorCycleSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0, verbose_name='駐車場No')),
                ('room_no', models.IntegerField(default=0, verbose_name='部屋番号')),
                ('date', models.DateField(blank=True, null=True, verbose_name='年月')),
                ('status_of_use', models.CharField(choices=[('空き', '空き'), ('使用中', '使用中')], default='空き', max_length=6, verbose_name='使用状況')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='備考')),
            ],
        ),
    ]
