# Generated by Django 5.2.8 on 2025-11-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoukakiType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='品番')),
                ('shoukaki_type', models.CharField(max_length=128, verbose_name='種類')),
                ('keisiki', models.CharField(max_length=128, verbose_name='形式番号')),
                ('maker', models.CharField(blank=True, max_length=128, null=True, verbose_name='製造会社')),
                ('valid_period', models.IntegerField(default=10, verbose_name='有効期間')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='購入価格')),
                ('alive', models.BooleanField(default=True, verbose_name='有効')),
            ],
        ),
        migrations.CreateModel(
            name='Shoukaki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='No')),
                ('location', models.CharField(max_length=32, verbose_name='設置場所')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='設置日')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='点検日')),
                ('made_year', models.IntegerField(default=1999, verbose_name='製造年')),
                ('made_no', models.CharField(max_length=64, unique=True, verbose_name='製造番号')),
                ('comment', models.TextField(blank=True, verbose_name='備考')),
                ('alive', models.BooleanField(default=True, verbose_name='有効')),
                ('shoukaki', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shoukaki.shoukakitype')),
            ],
        ),
    ]
