# Generated by Django 5.2.8 on 2025-11-26 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_user_flg', models.BooleanField(default=False, verbose_name='仮登録')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明文')),
                ('alive', models.BooleanField(default=True, verbose_name='有効')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('only_manager', models.BooleanField(default=False, verbose_name='管理者専用')),
            ],
        ),
    ]
